<?php

/**
 * Implements hook_theme().
 */
function d3tagcloud_theme($existing, $type, $theme, $path) {
  return [
    'gpthesaurus_list_type_switcher_block' => [
      'template' => 'glossary-list-type-switcher',
      'variables' => [
        'topic_page_link' => '',
        'topic_link_classes' => [],
        'alphabetically_page_link' => '',
        'alphabetically_link_classes' => [],
        'download_link' => '',
      ]
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function d3tagcloud_preprocess_block(&$variables) {
  switch ($variables['base_plugin_id']) {
    case 'search_api_sorts_block':
      if ($variables['elements']['#id'] == 'sortbyviewjurisprudenceindexeddisplayalljurisprudence') {
        $items = &$variables['content']['links']['#items'][0];
        if ($items['#order'] == 'desc') {
          $label = t('Sort by least recent');
        }
        else {
          $label = t('Sort by most recent');
        }
        $items['#label'] = $label;
        unset($items['#order_indicator']);
      }
      break;

    default:
      break;

  }
}
